# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Gurwinder Singh
title: GPU Software Development Engineer @ Intel
email: sgurwinderr@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: dreamdeor.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  sgurwinderr
linkedin_username: sgurwinderr
orcid_username: 0000-0002-8999-4317
googlescholar_username: bjywFLAAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Gurwinder Singh, a dedicated GPU Software Development Engineer currently employed at Intel. 
  My expertise spans various areas including AI (Directml), OGL & Vulkan, Virtualization (KVM, ESXI...), and Windows Test Automation. 
  In addition to my professional work, I've had the privilege of sharing my knowledge as an instructor at Chitkara University, teaching courses on Game Development, AR/VR, and Graphics Programming.
  I've actively contributed to academia through the publication of multiple research papers. 
  Moreover, I've made significant strides in the realm of AR/VR technology, having filed patents and secured grants for prototyping AR/VR applications.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Intel
        sub_title: GPU Software Development Engineer
        caption: June 2021 - Present
        description: | # this will include new lines to allow paragraphs
          As a GPU Software Development Engineer at Intel, I am responsible for Developing and Automating Server Graphics Components.
          My work involves Developing, Automating, and Debugging various server graphics components such as DirectML, Ray Tracing, GuC logs, ETL logs, vGPU scheduling, workload profiling, firmware management, and telemetry data.
          I have created an Framework for Windows Cloud Gaming Stack, which includes validators, workload profiling, 3D debugging, and Telemetry Data.
          Additionally, I have skillfully architected an Framework for the Server Graphics Virtualization Solution for KVM, Qemu & Libvirt.
          I have also engineered Test Automation flows specifically designed for virtualized machines on the Windows platform, thereby enhancing testing efficiency and accuracy.
      - layout: right
        title: Chitkara University
        sub_title: Research Assistant
        caption: May 2018 - May 2021
        description: | # this will include new lines to allow paragraphs
           At Chitkara University, I served as a Research Assistant at Centre of Excellence for AR/VR and Instructor @ GameDepartment.
           As an Instructor, I taught courses on game development, augmented reality/virtual reality, graphics programming, and game architecture.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Chitkara University
        sub_title: M.E CSE
        caption: 2018-2021
        description: | # this will include new lines to allow paragraphs
          During Master of Engineering in Computer Science at Chitkara University, I worked on several significant projects and achievements. I published 5 research papers and secured grants exceeding INR 10 Lakhs for prototyping AR/VR applications. 
          Additionally, I filed 3 patents related to AR/VR technology.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Published Research Article in Springer Journal 'Multimedia Tools and Applications 2023
      - Published Research Article in 'International Conference on Advancing and Redesigning Education' 2023
      - Delivered a lecture on Mathematical Visualization for Learning at Universiti Teknologi PETRONAS, Malaysia (2022)
      - Award of Academic Excellence by Chitkara University (2021)
      - Runner Up of BRIC Technology Exposition 2020 for Medical Devices
      - Winner of the Novate+ NewGen IEDC Grant of Rs 2.5 Lakhs (2020)
      - Delivered a 5-day National Level Faculty Development Program on Disruptive Technologies: AR and its Application (2020)
      - Winner of the National Level AR/VR VARCOE Startup Competition at IIT Bhuvneshwar (2020)
      - Winner of the TechSpardha 2k19 National Level Prototyping Hackathon (2019)
      - Winner of the Novate+ 2019 NewGen IEDC Grant of Rs 2.5 Lakhs (2019)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
