# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Gurwinder Singh
title: GPU Software Development Engineer @ Intel
email: sgurwinderr@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://sgurwinderr.github.io/blog/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  sgurwinderr
linkedin_username: sgurwinderr
orcid_username: 0000-0002-8999-4317
googlescholar_username: bjywFLAAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced in both industry and academia, I bring a versatile background in GPU software development and research. I specialize in optimizing and advancing AI and graphics technologies. With expertise in Py Torch, C++, Python, and graphics APIs such as OpenGL, Vulkan, and DirectX, I am dedicated to pushing the limits of AI-accelerator/GPU integration.
  Prior to this, as a Research Assistant at CURIN, Chitkara University, I developed Unity, OpenGL, and Vulkan applications for advanced trigonometry and linear algebra projects, alongside creating AR/VR tools for educational enhancement.
  My research journey includes publishing eight papers in SCI Journals and IEEE, spanning topics such as advanced video analysis using Video Vision Transformers (Intel DTTC 2024), AR applications for enhancing spatial skills in trigonometry (Hyperspace AR, Springer US), and interactive tools for visualizing linear algebra concepts (AR for Linear Algebra Visualization, IEEE).
  Further, I've filed three patents in AR/VR technology and secured over INR 10 Lakhs in grants for prototyping innovative applications. Awards include winning the BRIC Technology Exposition 2020 and the Novate+ NewGen IEDC Grant from the Government of India. I've also delivered lectures internationally, including 'Computational Models with LLM' and 'Mathematical Visualization for Learning' at Universiti Teknologi PETRONAS, Malaysia.
  Passionate about leveraging technology to drive innovation, I excel in bridging research insights with practical applications, aiming to push the boundaries of AI, graphics, and educational tools.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Intel
        sub_title: GPU Software Development Engineer
        caption: June 2021 - Present
        description: | # this will include new lines to allow paragraphs
          Experienced GPU Software Development Engineer specializing in driver optimization, Pytorch, C++ programming, Python scripting, and advanced graphics APIs like OpenGL, Vulkan, and DirectX.
          Currently contributing to Intel's Habana Labs, focusing on advancing AI-accelerator/GPU integration through the optimization of Intel PyTorch Extension (IPEX) for AI accelerators and delivering key features for data center GPUs
      - layout: right
        title: Chitkara University
        sub_title: Research Assistant
        caption: May 2018 - May 2021
        description: | # this will include new lines to allow paragraphs
          Experienced in leading research projects and developing simulation software utilizing AR and VR technologies. Specializes in creating immersive experiences to enhance learning in subjects like trigonometry and linear algebra, as well as developing AI-driven medical devices.
          Significant contributions have been made to research, with a total of six papers published in esteemed SCI Journals and IEEE, including four as the primary author and two as a co-author. Additionally, a strong commitment to innovation is demonstrated through the filing of three patents that advance the frontier of AR/VR technology.
          Awards include winning the BRIC Technology Exposition 2020, sponsored by the National Research Development Corporation (NRDC) and FICCI, as well as securing the Novate+ NewGen IEDC Grant 2019 & 2020 organized by the Government of India. Further recognition includes winning the AR/VR Startup Competition 2019 at IIT Bhubaneswar and achieving first place at the TechSpardha 2k19 National Level Prototyping Hackathon 2019.
          Efforts in securing grants have played a crucial role, with over INR 10 Lakhs secured for the prototyping and development of cutting-edge AR/VR applications.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Chitkara University
        sub_title: M.E CSE
        caption: 2018-2021
        description: | # this will include new lines to allow paragraphs
          During Master of Engineering in Computer Science at Chitkara University, I worked on several significant projects and achievements. I published 5 research papers and secured grants exceeding INR 10 Lakhs for prototyping AR/VR applications. 
          Additionally, I filed 3 patents related to AR/VR technology.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Published Research Article in Intel DTTC 2024 'Advanced video analysis using Video Vision Transformers for 50% increase in frame corruption detection'.
      - Delivered Lectures at University Technology PETRONAS, Malaysia 2023 regarding ‘Computational Models with LLM'.
      - Delivered Lectures at University Technology PETRONAS, Malaysia 2022 regarding 'Mathematical Visualization for Learning'
      - Published Research Article in Springer Journal 'Multimedia Tools and Applications 2023
      - Published Research Article in 'International Conference on Advancing and Redesigning Education' 2023
      - Delivered a lecture on Mathematical Visualization for Learning at Universiti Teknologi PETRONAS, Malaysia (2022)
      - Award of Academic Excellence by Chitkara University (2021)
      - Runner Up of BRIC Technology Exposition 2020 for Medical Devices
      - Winner of the Novate+ NewGen IEDC Grant of Rs 2.5 Lakhs (2020)
      - Delivered a 5-day National Level Faculty Development Program on Disruptive Technologies: AR and its Application (2020)
      - Winner of the National Level AR/VR VARCOE Startup Competition at IIT Bhuvneshwar (2020)
      - Winner of the TechSpardha 2k19 National Level Prototyping Hackathon (2019)
      - Winner of the Novate+ 2019 NewGen IEDC Grant of Rs 2.5 Lakhs (2019)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
